### ISSUE TITLE
Add a Swipe from left to right framer motion in page transistion

### ISSUE THREAD

**Issue by primeTanM** [primeTanM/portfolio#1]
I have a basic fade in fade out framer motion added.If someone can change it to "swipe from right to left" kind of animation, it would be helpful.

**Comment by Dhanunjay18** [comment]
Hey can u plz assign this issue to me

**Comment by Aryan-Bhatt-pro** [comment]
Hi, can you please assign the issue to me?

**Comment by primeTanM** [comment]
@Aryan-Bhatt-pro, sure you can take up this issue

> Hey can u plz assign this issue to me
@Dhanunjay18 I am opening another issue.You can take up that

**Comment by primeTanM** [comment]
@Aryan-Bhatt-pro are you working on it?

**Comment by Aryan-Bhatt-pro** [comment]
yes, sorry was busy lately, will try to complete it asap

**Comment by Aryan-Bhatt-pro** [comment]
Have created the PR regrading this issue. Please let me know if this suffices.

**Comment by primeTanM** [comment]
@Aryan-Bhatt-pro Hey, the effect is right, can you increase the transistion speed so it looks smoother

**Comment by primeTanM** [comment]
@Aryan-Bhatt-pro Also, there seems to be a scroll bar when we transistion to another page, usually blogs and contact page.So if possible fix that also
![image](https://user-images.githubusercontent.com/72358736/195480929-0dc782c0-29dd-4ddd-bb73-db20223c17f1.png)

**Comment by Aryan-Bhatt-pro** [comment]
ok will fix it

**Comment by Aryan-Bhatt-pro** [comment]
Hey @primeTanM, I have changed the transition speed between the pages. Regarding the scroll bar, I don't think it's due to the animation of pages or my code changes. It was there before also. Maybe you can open a new issue regarding this.
Regarding the page transition let me know if it suffices.

**Comment by primeTanM** [comment]
@Aryan-Bhatt-pro Yeah, it's fine.Thanks
