### ISSUE TITLE
Make it so that text doesnt overlap over the navbar

### ISSUE THREAD

**Issue by primeTanM** [primeTanM/portfolio#10]
When zoomed in, the content below the navbar overlaps it(for eg in About page).Kindly fix this.
If you can add some responsive typography it would be very helpful

**Comment by anshss** [comment]
@primeTanM can you please assign this issue to me?

**Comment by segunojo1** [comment]
@primeTanM please assign this issue to me

**Comment by primeTanM** [comment]
@anshss sure you can take up

**Comment by primeTanM** [comment]
@anshss Are you working on this

**Comment by nirajpdn** [comment]
I want to work on this.

**Comment by primeTanM** [comment]
@nirajpdn yeah take it up and kindly acknowledge if you are doing so

**Comment by nirajpdn** [comment]
Sure @primeTanM.
