### ISSUE TITLE
Add navigation arrows between pages

### ISSUE THREAD

**Issue by primeTanM** [primeTanM/portfolio#11]
Add navigation arrows at extreme right/left and vertically center to navigate between next and previous pages.You can use this arrow icon from react-icons library.
![image](https://user-images.githubusercontent.com/72358736/194921963-d87066af-68d7-4934-ad19-a685e5b9f69a.png)

Additionally you can also add gesture like holding mouse btn and swiping right or left to navigate

**Comment by whiletrueee** [comment]
@primeTanM i would like to work on this and complete the task can you assign it to me please

**Comment by primeTanM** [comment]
@flying-solo you can take this up

**Comment by primeTanM** [comment]
@flying-solo will you work on this?

**Comment by whiletrueee** [comment]
yes i will work on this

**Comment by whiletrueee** [comment]
@primeTanM created the pr for this issue have a look on it
