### ISSUE TITLE
Hover effect not working properly in instagram icon

### ISSUE THREAD

**Issue by primeTanM** [primeTanM/portfolio#16]
So in contact page, while other buttons are working fine,when we hover on insta button, it changes color without any transistion.This could be due to the gradient color I applied

Kindly resolve this

**Comment by Sodium-Sharma** [comment]
hey @primeTanM i would like to help you with this. Assign it to me.

**Comment by primeTanM** [comment]
@Sodium-Sharma done

**Comment by kd1729** [comment]
@primeTanM Using gradients for animations (or transitions) is unfortunately not by any browser at the moment. 

Kindly take a look at https://stackoverflow.com/questions/17952468/css-background-gradient-transition-not-working

**Comment by kd1729** [comment]
@primeTanM I have resolved this issue, kindly check. #28
