### ISSUE TITLE
Scroll bar appearing due to page transistion

### ISSUE THREAD

**Issue by primeTanM** [primeTanM/portfolio#18]
So there seems to a scrollbar appearing, when when we switch to the blog and contact page.Kindly fix it

**Comment by bugsforbucks** [comment]
can you explain this issue a bit more

**Comment by whiletrueee** [comment]
@primeTanM i would like to work on it please assign it to me

**Comment by primeTanM** [comment]
@flying-solo sure

**Comment by whiletrueee** [comment]
@primeTanM  i have fixed the issue and created a pr can you check it 😊

**Comment by primeTanM** [comment]
@flying-solo that's great, thanks

**Comment by primeTanM** [comment]
@flying-solo you can fix the scroll issue again.I have reopened the issue

**Comment by flying-solo** [comment]
@primeTanM  hacktober fest accepted this , i guess it was not needed to reopen this issue

**Comment by primeTanM** [comment]
@flying-solo I have closed PR but the issue is still there
