### ISSUE TITLE
Add big quotes at the start of para in About Page

### ISSUE THREAD

**Issue by primeTanM** [primeTanM/portfolio#4]
Kindly add a big double shaped quote at the start of the paragraph in About page.Make it so that one quote is pink and one is white

**Comment by nalin-programmer** [comment]
Assign me this task

**Comment by primeTanM** [comment]
Sure, go ahead

**Comment by nalin-programmer** [comment]
ok

**Comment by nalin-programmer** [comment]
I have done the task, please merge the pull request.

**Comment by nalin-programmer** [comment]
And label this with hacktoberfest-accept
